name: Alpine-Image

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - run: sudo apt-get install qemu-utils bzip2
    - run: wget https://raw.githubusercontent.com/alpinelinux/alpine-make-vm-image/v0.6.0/alpine-make-vm-image && echo 'a0fc0b4886b541bb4dd7b91b4e1e99719a1700da  alpine-make-vm-image' | sha1sum -c || exit 1
      name: install alpine-make
    - run: chmod +x ./example/configure.sh && chmod +x ./alpine-make-vm-image
      name: Scripts Permission
    - run: mkdir ./latest
      name: Scripts Permission
    - run: >-
        sudo ./alpine-make-vm-image 
        --image-format qcow2 
        --image-size 2G 
        --repositories-file example/repositories 
        --packages "$(cat example/packages)" 
        --script-chroot 
        $FILENAME -- ./example/configure.sh && bzip2 -z $FILENAME && mv $FILENAME.bz2 ./latest/

      name: build
      env:
        CI: true
        FILENAME: 'alpine-image.qcow2'
    - name: Upload artifact
      uses: actions/upload-artifact@v1
      with:
        name: Alpine Image
        # Directory containing files to upload
        path: latest/
