name: Alpine-Image

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - run: sudo apt-get install qemu-utils
    - run: wget https://raw.githubusercontent.com/alpinelinux/alpine-make-vm-image/v0.6.0/alpine-make-vm-image && echo 'a0fc0b4886b541bb4dd7b91b4e1e99719a1700da  alpine-make-vm-image' | sha1sum -c || exit 1
      name: install alpine-make
    - run: chmod +x ./example/configure.sh && chmod +x ./alpine-make-vm-image
      name: Scripts Permission
    - run: >-
        ./alpine-make-vm-image 
        --image-format qcow2 
        --image-size 2G 
        --repositories-file example/repositories 
        --packages "$(cat example/packages)" 
        --script-chroot 
        alpine-virthardened-$(date +%Y-%m-%d).qcow2 -- ./example/configure.sh

      name: build
      env:
        CI: true
